### ISSUE TITLE
Add config parameter to tag lower or upper-case

### ISSUE THREAD

**Issue by varac** [afewmail/afew#144]
I'd like to have the ability to tag mails based on different filters with a global paramter that would translate all tags to lower- (maybe also upper-) case.
The reationale behind this is that without I get tags from different filters that differe only in their case ('Projects', 'projects', 'PROJECTS') and these clutter the UI of alot.
I know I could translate tag by tag but I'd prefer a generic solution.

i.e. 

```
afew --tag --new --lowercase
```

**Comment by GuillaumeSeren** [comment]
Hey @varac 
it is a bit strange to have the same tag uppercase and lowercase because you can easily choose one and change the other.
Anyway this could be neat to have a 'ignore case' option, but to me it is really depended on a particular use-case, so it should be better to have it as a configuration option.
It could also be done using the 'tags' options in the config.

**Comment by flokli** [comment]
I think that's outside the scope of afew. There is no real way in matching tags lowercase by notmuch alone, and I don't really see a need to support this in afew.
Please fix your filters to only use one case and retag existing mails.
