### ISSUE TITLE
Should afew's MailMover move emails out of Maildir's /new or /tmp subfolders ?

### ISSUE THREAD

**Issue by dannyob** [afewmail/afew#196]
I use afew as a post-new notmuch hook, after I've synced my mail using [mbsync](http://isync.sourceforge.net/mbsync.html) but before my new mail has been read by my MUA. As a result, new mail is still in the /new sub-directory (and indexed as such by notmuch). 

This *also* means that each of those mail's filenames has not yet had any metadata appended, which means that filename doesn't have a colon in it, which means that MailMover's [file renaming strategy](https://github.com/afewmail/afew/blob/9a8309b30b536cffeeeb1901a3f0e33b11552ded/afew/MailMover.py#L41) breaks.  The end result is that the UID element of the mail is not stripped out, leading to conflicting UIDs in the destination Maildir.

I have a small patch for this for afew, which limits moves to files in the "/cur" subfolder. 

Does that seem the right approach? Or is this something better handled by calling afew at a different point?

**Comment by mjg** [comment]
On moving: I would think we have either "no metadata no UID" or "metadata and UID", but I may be wrong. In any case `/new` should be moved to `/new`, not `/cur`, shouldn't it?

On the hook ( ;) ): I think that `afew -m` belongs in the pre-new hook, `afew -t ` in the post-new hook. The reasoning is the following: afew (folderfilter+mailmover) is about keeping a mapping between folders and tags. In your notmuch-based MUA, you operate on tags and want that action to be reflected in a folder change. So, once you change tags in your MUA, the tags are "out of snyc" with the locations. In that state, `afew -m` is what makes the folders follow the tags; then, `mbsync --push` is what pushes these changes to the IMAP server; `mbsync --pull` brings in new mail into specific folders; `notmuch new` makes them known to the notmuch db; `afew -t` makes the locations of the new mails be reflected in the tags. So:

pre-new: afew -m; mbsync
post-new: afew -t -n

**Comment by mjg** [comment]
So, I've checked the maildir and mbsync docs, and the upshot is:

**Whoever moves maildir mail from `/new` to `/cur` is required to add `:metadata`.** So, I suggest that afew's MailMover would move from `/new` to `/new` and from `/cur` to `cur`.

**UIDs in a maildir using the native mbsync format need to be unique.** So, if the message has a UID and is being moved somewhere else then the UID has to be removed (so that it will be reassigned one by mbsync). A UID without `:metadata` should happen within `/new` only, but it's best not to depend on this. So I suggest afew's MailMover to match on `,U=[0-9]+` and remove only that.

**Comment by mjg** [comment]
Addition, sorry: To be extra safe, regenerating the name (as MM currently does) is best. Patch coming.

**Comment by dannyob** [comment]
This looks great, thankyou!
