### ISSUE TITLE
write documentation

### ISSUE THREAD

**Issue by teythoon** [afewmail/afew#23]

**Comment by lucc** [comment]
Any news on this? What can people besides @teythoon do to work on this issue?

**Comment by bjoernb** [comment]
No one.

**Comment by pohly** [comment]
I found afew via https://notmuchmail.org/initial_tagging/ which directly links to the repo. Then I was struggling to understand the main README.rst because (as discussed in this issue) it left some open questions.

But then I found the more extensive documentation in the docs folder respectively at https://afew.readthedocs.io/en/latest/ and that was good enough.

I suggest to shorten the main README.rst so that it doesn't duplicate information from the full documentation (basically just leaving a summary and a link) and then close this issue. Agreed? I can prepare a PR.

**Comment by flokli** [comment]
@pohly yes, sounds good, thanks :-)
