### ISSUE TITLE
Execution failed

### ISSUE THREAD

**Issue by domingoUnican** [afewmail/afew#257]
Dear all,

I just installed afew using pip (python 3.7). After following the instructions in the "quick install" section, I got the following error:

Hook stderr:Error: post-new hook execution failed: Exec format error
Error: post-new hook failed with status 1

The error is related with:
$ mkdir -p path/to/maildir/.notmuch/hooks
$ touch path/to/maildir/.notmuch/hooks/post-new
If I delete the file post-new, then it works.

I am using Mac Os X Mojave.

Thank you very much for your help.

**Comment by bjoernfan** [comment]
The next step in the quickstart is this:

    Then edit the post-new file to contain:
    
    #!/bin/sh
    $HOME/.local/bin/afew --tag --new

The touch thing and then edit content threw me off for a second as well.

Also, one thing that's missing is that it needs to be executable, so you need to run chmod +x on that file before it will work, otherwise you'll get another permission error. I'll see if I can make a docs PR about that.

Also, of course, change the path to afew in that file to whereever that file is on your system. For me installed via apt it's here: /usr/bin/afew.

**Comment by domingoUnican** [comment]
Thanks! that was it.
