### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by aidecoe** [afewmail/afew#53]
afew is a cool tool which could be added to various distribution repositories. I have added afew to my experimental Gentoo repo and I am looking forward to add first official release of afew to official Gentoo repository. The list of issues is not so long, so I think fixing them and making a release should be so time-consuming.

**Comment by benjaminfrank** [comment]
Any update on the issue?
I created a homebrew formula https://github.com/Homebrew/homebrew/pull/41280 but having sematic versioning would make things much easier.
 maybe an initial 0.0.1 so various package managers could package something?

**Comment by bfontaine** [comment]
Yes it would be great to have a version so we could move that in the Homebrew core.

**Comment by GuillaumeSeren** [comment]
Hey there ! @aidecoe 
I agree that we need to cut a release, to help packaging and distributions.

As the project is changing maintainer with @teythoon stepping back I think it is a good time to cut the first release, due to the age and features of it, I think this could be a v1, but this decision has to be community based, so I will searching for a way to vote.

**Comment by flokli** [comment]
Yesterday, version 1.0.0 was released and uploaded to PyPi. closing here :-)
